// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_index from "./routes/about/index.tsx";
import * as $contact_error_index from "./routes/contact/error/index.tsx";
import * as $contact_index from "./routes/contact/index.tsx";
import * as $contact_success_index from "./routes/contact/success/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $notes_index from "./routes/notes/index.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about/index.tsx": $about_index,
    "./routes/contact/error/index.tsx": $contact_error_index,
    "./routes/contact/index.tsx": $contact_index,
    "./routes/contact/success/index.tsx": $contact_success_index,
    "./routes/index.tsx": $index,
    "./routes/notes/index.tsx": $notes_index,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
